appium.server.host=127.0.0.1
appium.server.port=4723
app.package=com.credobusiness
app.activity=com.credobusiness.MainActivity
platform.name=Android
automation.name=UiAutomator2
device.name=emulator-5554
no.reset=false
default.wait.seconds=10
